import './globals.css'
import Link from 'next/link';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'HealthCare Pro',
  description: 'Medical Management System',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50`}>
        <nav className="bg-white shadow-sm">
          <div className="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
            <h1 className="text-xl font-bold text-primary-800">
            <Link href="/">HealthCare Pro</Link>
            </h1>
            <div className="flex space-x-6">
              <a href="/dashboard" className="text-gray-600 hover:text-primary-600">Dashboard</a>
              <a href="/patients" className="text-gray-600 hover:text-primary-600">Patients</a>
              <a href="/appointments" className="text-gray-600 hover:text-primary-600">Appointments</a>
              <a href="/doctors" className="text-gray-600 hover:text-primary-600">Doctors</a>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}









// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
